on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: A job to add a medium Article to instapaper account
    steps:
      - name: Add example article
        uses: irfansofyana/instapaper-actions@v1.0.0
        with:
          username: ${{ secrets.INSTAPAPER_USERNAME }}
          password: ${{ secrets.INSTAPAPER_PASSWORD }}
          url: https://medium.com/@gibinfrancis/software-architect-journey-ca9398546608
          title: Software Architect — Journey
          selection: This article is added by Github Action