on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: A job to add a Github Article to instapaper account
    steps:
      - name: Add example article
        uses: irfansofyana/instapaper-actions@v0.1.4
        with:
          username: ${{ secrets.INSTAPAPER_USERNAME }}
          password: ${{ secrets.INSTAPAPER_PASSWORD }}
          url: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action
          title: Creating Javascript Action
          selection: This article is added by Github Action